name: table2chart
author: thinkphp 
current: v1.3 
category: utilities 
tags: [google,chart,table,api,interface,table2chart,accessible]
docs: http://github.com/thinkphp/table2chart/blob/master/Docs/table2chart.md
demo: http://thinkphp.github.com/table2chart/
